name: siger_pangan_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Pendaftaran aset gambar sesuai dengan folder assets/images kamu
  assets:
    - assets/images/logo bappanas.jpeg
    - assets/images/logo DKPTPH Prov Lampung.jpeg
    - assets/images/logo provinsi lampung.jpeg
    - assets/images/logo stop boros pangan.jpeg